# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpr',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpr',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
