# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpr', '0003_lpr_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lpr',
            name='timestamp',
        ),
    ]
