# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpr', '0005_auto_20161021_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LPR',
        ),
    ]
