# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lpr', '0006_delete_lpr'),
    ]

    operations = [
        migrations.CreateModel(
            name='lpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_revisions', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('client', models.CharField(max_length=255)),
                ('interest_type', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('prospect', models.CharField(max_length=255)),
                ('lessor', models.CharField(max_length=255)),
                ('lessor_address1', models.CharField(max_length=255)),
                ('lessor_address2', models.CharField(max_length=255)),
                ('lessor_city', models.CharField(max_length=255)),
                ('lessor_state', models.CharField(max_length=255)),
                ('lessor_zip', models.CharField(max_length=255)),
                ('lessor_phone', models.CharField(max_length=255)),
                ('lessor_email', models.CharField(max_length=255)),
                ('lessor_ssn_tin', models.CharField(max_length=255)),
                ('lessor_interest', models.CharField(max_length=255)),
                ('royalty', models.DecimalField(decimal_places=4, max_digits=4)),
                ('gross_acres', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_acres', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bonus_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bonus', models.DecimalField(decimal_places=2, max_digits=15)),
                ('check_number', models.CharField(max_length=255)),
                ('legal', models.TextField()),
                ('drilling_platform', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('primary_term_years', models.IntegerField()),
                ('extension_term_years', models.IntegerField()),
                ('ogml_only', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('horz_pugh', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('ver_pugh', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('depth_limit', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('cont_dev', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('cont_dev_days', models.IntegerField()),
                ('damages', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('swd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('orri_wi', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('no_surface', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('specific_surface', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('free_royalty', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('pooling_limit', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('max_pooling_acreage', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('min_pooling_acreage', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('consent_assign', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('shut_in', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('water_well', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('lease_image', models.FileField(upload_to='uploads/lprs/leases/')),
                ('memo_image', models.FileField(upload_to='uploads/lprs/memos/')),
                ('payment_image', models.FileField(upload_to='uploads/lprs/checks/')),
                ('plat_image', models.FileField(upload_to='uploads/lprs/plats/')),
                ('source_deed_image', models.FileField(upload_to='uploads/lprs/source_deeds/')),
                ('mor_image', models.FileField(upload_to='uploads/lprs/mors/')),
                ('runsheet_image', models.FileField(upload_to='uploads/lprs/runseets/')),
                ('w9_image', models.FileField(upload_to='uploads/lprs/w9s/')),
                ('curative_image', models.FileField(upload_to='uploads/lprs/curative/')),
            ],
        ),
    ]
