# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr', '0007_lpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpr',
            name='interest_type',
            field=models.CharField(choices=[('MD', 'Mineral Deed'), ('OGML', 'Oil and Gas Lease')], max_length=4),
        ),
    ]
