# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpr', '0012_remove_lpr_ogml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpr',
            old_name='lease_revisions',
            new_name='Lease_Revisions',
        ),
        migrations.RenameField(
            model_name='lpr',
            old_name='md',
            new_name='Mineral_Deed',
        ),
    ]
