# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr', '0015_auto_20161021_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpr',
            old_name='lessor_Address1',
            new_name='lessor_Address_1',
        ),
        migrations.RenameField(
            model_name='lpr',
            old_name='lessor_Address2',
            new_name='lessor_Address_2',
        ),
        migrations.RenameField(
            model_name='lpr',
            old_name='orri_wi',
            new_name='oRRI_WI',
        ),
        migrations.AlterField(
            model_name='lpr',
            name='max_pooling_acreage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lpr',
            name='min_pooling_acreage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
