# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpr', '0020_lpr_ogml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpr',
            old_name='lease_revisions',
            new_name='revisions',
        ),
    ]
